# $FreeBSD: head/www/sogo3-activesync/Makefile 414642 2016-05-05 13:08:29Z acm $

PKGNAMESUFFIX=		-activesync

MAINTAINER=		euan@potensol.com

CONFLICTS=		sogo[2-3]-[0-9]*

OPTIONS_SLAVE=		ACTIVESYNC

MASTERDIR=		${.CURDIR}/../sogo3

.include "${MASTERDIR}/Makefile"
