# $FreeBSD: head/www/sogo2-activesync/Makefile 414488 2016-05-02 23:06:21Z acm $

PKGNAMESUFFIX=		-activesync

MAINTAINER=		euan@potensol.com

CONFLICTS=		sogo2-[0-9]* sogo3-[0-9]*

OPTIONS_SLAVE=		ACTIVESYNC

MASTERDIR=		${.CURDIR}/../sogo2

.include "${MASTERDIR}/Makefile"
