# $FreeBSD$

PKGNAMESUFFIX=		-activesync

MAINTAINER=		euan@potensol.com

LICENSE=		GPLv2

MASTERDIR=		${.CURDIR}/../sogo

DESCR=			${.CURDIR}/pkg-descr

OPTIONS_DEFAULT+=	ACTIVESYNC

.include "${MASTERDIR}/Makefile"
