# $FreeBSD: head/www/sogo-activesync/Makefile 402361 2015-11-24 13:33:56Z amdmi3 $

PKGNAMESUFFIX=		-activesync

MAINTAINER=		euan@potensol.com

CONFLICTS=		sogo-[0-9]*

OPTIONS_SLAVE=		ACTIVESYNC

MASTERDIR=		${.CURDIR}/../sogo

.include "${MASTERDIR}/Makefile"
